stages:
  - lint

eslint:
  stage: lint
  variables:
    NODE_VERSION: 16.14.2
  script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use
    - nvm install $NODE_VERSION
    - npm install
    - npm run lint
